name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Start services
      run: |
        docker run -d --name web -p 3000:3000 \
          --health-cmd="curl --fail http://localhost:3000 || exit 1" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=5 \
          -v ${{ github.workspace }}:/app node:14 \
          sh -c "cd /app && npm install && npm start"
        sleep 10  # サーバーの起動を待つために10秒待機

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
